[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/executables/*"
  to = "/executables/:splat"
  force=true
  status = 200

[[redirects]]
  from = "/multiplayer/*"
  to = "/multiplayer/:splat"
  force=true
  status = 200

