[headers]
for = "/*"

[headers.values]
  Cross-Origin-Opener-Policy = "cross-origin"
  # Remove restrictive setting for embedding
  Cross-Origin-Embedder-Policy = "*"
  # Remove restrictive setting for resource policy
  Cross-Origin-Resource-Policy = "*"

[[redirects]]
  from = "/executables/*"
  to = "/executables/:splat"
  force=true
  status = 200

[[redirects]]
  from = "/multiplayer/*"
  to = "/multiplayer/:splat"
  force=true
  status = 200

