[headers]
for = "/*"

[headers.values]
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "require-corp"
  Cross-Origin-Resource-Policy = "coep=unsafe-none"

[[redirects]]
  from = "/executables/*"
  to = "/executables/:splat"
  force=true
  status = 200

[[redirects]]
  from = "/multiplayer/*"
  to = "/multiplayer/:splat"
  force=true
  status = 200

