[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/executables/*"
  to = "/executables/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/multiplayer/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "*"
  to = "/server-client-nodejs/frontend/:splat"
  status = 200
  force = true