[[headers]]
for = "/*"

[headers.values]
  Cross-Origin-Opener-Policy = "cross-origin"
  Cross-Origin-Embedder-Policy = "unsanitized-unsafe-inline"
  Cross-Origin-Resource-Policy = "cross-origin"

[[redirects]]
  from = "/executables/*"
  to = "/executables/:splat"
  force=true
  status = 200

[[redirects]]
  from = "/multiplayer/*"
  to = "/multiplayer/:splat"
  force=true
  status = 200

