[[headers]]
for = "/*"

[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
X-Frame-Options = "ALLOW-FROM https://astounding-profiterole-59052b.netlify.app/"
